"""Generate an owner-bound Apple Shortcut for David-Pi media backup."""

from __future__ import annotations

import plistlib
import uuid


SERVER_URL = "https://server.example-tail.ts.net"


def _uuid() -> str:
    return str(uuid.uuid4()).upper()


def _output(action_uuid: str, name: str) -> dict:
    return {
        "Value": {"OutputName": name, "OutputUUID": action_uuid, "Type": "ActionOutput"},
        "WFSerializationType": "WFTextTokenAttachment",
    }


def _token(attachment: dict, text: str = "\ufffc") -> dict:
    return {
        "Value": {"attachmentsByRange": {"{0, 1}": attachment}, "string": text},
        "WFSerializationType": "WFTextTokenString",
    }


def _repeat_item(*, property_name: str | None = None) -> dict:
    item = {"Type": "Variable", "VariableName": "Repeat Item"}
    if property_name:
        item["Aggrandizements"] = [
            {
                "Type": "WFPropertyVariableAggrandizement",
                "PropertyName": property_name,
                **({"PropertyUserInfo": "WFItemName"} if property_name == "Name" else {}),
            }
        ]
    return item


def _header(key: str, value: str | dict) -> dict:
    def field(payload: str | dict) -> dict:
        if isinstance(payload, str):
            return {"Value": {"string": payload}, "WFSerializationType": "WFTextTokenString"}
        return payload

    return {"WFItemType": 0, "WFKey": field(key), "WFValue": field(value)}


def _action(identifier: str, **parameters) -> dict:
    return {
        "WFWorkflowActionIdentifier": identifier,
        "WFWorkflowActionParameters": parameters,
    }


def build_backup_shortcut(credential: str, server_url: str = SERVER_URL) -> bytes:
    """Return an unsigned binary Shortcut containing one device credential."""
    if not credential or any(ch.isspace() for ch in credential):
        raise ValueError("A valid device credential is required")
    server_url = server_url.rstrip("/")
    if not server_url.startswith("https://"):
        raise ValueError("The Shortcut server URL must use HTTPS")

    loop_id = _uuid()
    status_uuid = _uuid()
    cursor_uuid = _uuid()
    photos_uuid = _uuid()
    empty_id = _uuid()
    each_id = _uuid()
    date_uuid = _uuid()
    upload_uuid = _uuid()

    cursor_ref = _output(cursor_uuid, "Dictionary Value")
    photo_filter = {
        "Value": {
            "WFActionParameterFilterPrefix": 1,
            "WFContentPredicateBoundedDate": False,
            "WFActionParameterFilterTemplates": [
                {
                    "Operator": 2,
                    "Property": "Date Taken",
                    "Removable": True,
                    "Values": {"Date": cursor_ref},
                }
            ],
        },
        "WFSerializationType": "WFContentPredicateTableTemplate",
    }
    photos_input = {"Type": "Variable", "Variable": _output(photos_uuid, "Photos")}
    auth_value = {
        "Value": {"string": f"Bearer {credential}"},
        "WFSerializationType": "WFTextTokenString",
    }
    name_value = _token(_repeat_item(property_name="Name"))
    date_value = _token(
        {"OutputName": "Formatted Date", "OutputUUID": date_uuid, "Type": "ActionOutput"}
    )
    file_body = _token(_repeat_item())

    actions = [
        _action(
            "is.workflow.actions.comment",
            WFCommentActionText=(
                "DAVID-PI GENERATED SHORTCUT\n"
                "Owner-bound, upload-only, private through Tailscale. The server chooses the owner.\n"
                "This Shortcut requests the next 200 originals, uploads them, and repeats until done."
            ),
        ),
        _action(
            "is.workflow.actions.comment",
            WFCommentActionText=(
                "Shortcuts generated by Shortcuts Playground.\n"
                "- Repeat up to 250 batches\n"
                "- Each batch asks David-Pi for its saved checkpoint\n"
                "- Leave Shortcuts open during the initial migration"
            ),
        ),
        _action(
            "is.workflow.actions.repeat.count",
            GroupingIdentifier=loop_id,
            WFControlFlowMode=0,
            WFRepeatCount=250,
        ),
        _action(
            "is.workflow.actions.downloadurl",
            UUID=status_uuid,
            WFURL=f"{server_url}/api/v1/ios-backup/status",
            WFHTTPMethod="GET",
            Advanced=True,
            ShowHeaders=False,
            WFHTTPHeaders={
                "Value": {"WFDictionaryFieldValueItems": [_header("Authorization", auth_value)]},
                "WFSerializationType": "WFDictionaryFieldValue",
            },
        ),
        _action(
            "is.workflow.actions.getvalueforkey",
            UUID=cursor_uuid,
            WFDictionaryKey="capture_after",
            WFGetDictionaryValueType="Value",
            WFInput=_output(status_uuid, "Contents of URL"),
        ),
        _action(
            "is.workflow.actions.filter.photos",
            UUID=photos_uuid,
            WFContentItemFilter=photo_filter,
            WFContentItemSortProperty="Date Taken",
            WFContentItemSortOrder="Oldest First",
            WFContentItemLimitEnabled=True,
            WFContentItemLimitNumber=200,
        ),
        _action(
            "is.workflow.actions.comment",
            WFCommentActionText=(
                "STOP WHEN CURRENT\n"
                "- Input is the current batch from Find Photos\n"
                "- An empty batch means every available item has reached David-Pi"
            ),
        ),
        _action(
            "is.workflow.actions.conditional",
            GroupingIdentifier=empty_id,
            WFControlFlowMode=0,
            WFCondition=101,
            WFInput=photos_input,
        ),
        _action("is.workflow.actions.notification", WFNotificationActionBody="David-Pi backup is up to date."),
        _action("is.workflow.actions.exit"),
        _action(
            "is.workflow.actions.conditional",
            GroupingIdentifier=empty_id,
            WFControlFlowMode=2,
        ),
        _action(
            "is.workflow.actions.comment",
            WFCommentActionText=(
                "UPLOAD THIS BATCH\n"
                "- Input is the 200-or-smaller batch from Find Photos\n"
                "- Repeat Item is sent as the original file\n"
                "- Date Taken advances the server checkpoint after verification"
            ),
        ),
        _action(
            "is.workflow.actions.repeat.each",
            GroupingIdentifier=each_id,
            WFControlFlowMode=0,
            WFInput=_output(photos_uuid, "Photos"),
        ),
        _action(
            "is.workflow.actions.format.date",
            UUID=date_uuid,
            WFDate=_token(_repeat_item(property_name="Date Taken")),
            WFDateFormat="Custom",
            WFDateFormatStyle="Custom",
            WFDateFormatString="yyyy-MM-dd'T'HH:mm:ssXXXXX",
        ),
        _action(
            "is.workflow.actions.downloadurl",
            UUID=upload_uuid,
            WFURL=f"{server_url}/api/v1/ios-backup/upload-file",
            WFHTTPMethod="POST",
            WFHTTPBodyType="File",
            WFRequestVariable=file_body,
            Advanced=True,
            ShowHeaders=False,
            WFHTTPHeaders={
                "Value": {
                    "WFDictionaryFieldValueItems": [
                        _header("Authorization", auth_value),
                        _header("X-David-Pi-Filename", name_value),
                        _header("X-David-Pi-Captured-At", date_value),
                    ]
                },
                "WFSerializationType": "WFDictionaryFieldValue",
            },
        ),
        _action(
            "is.workflow.actions.repeat.each",
            GroupingIdentifier=each_id,
            WFControlFlowMode=2,
        ),
        _action(
            "is.workflow.actions.repeat.count",
            GroupingIdentifier=loop_id,
            WFControlFlowMode=2,
        ),
        _action("is.workflow.actions.notification", WFNotificationActionBody="David-Pi backup finished."),
    ]

    workflow = {
        "WFWorkflowActions": actions,
        "WFWorkflowClientVersion": "2607.0.4",
        "WFWorkflowClientRelease": "26A0000a",
        "WFWorkflowMinimumClientVersion": 900,
        "WFWorkflowMinimumClientVersionString": "900",
        "WFWorkflowIcon": {
            "WFWorkflowIconGlyphNumber": 59714,
            "WFWorkflowIconStartColor": 4251333119,
        },
        "WFWorkflowName": "Back Up to David-Pi",
        "WFWorkflowHasOutputFallback": False,
        "WFWorkflowImportQuestions": [],
        "WFWorkflowInputContentItemClasses": [],
        "WFWorkflowOutputContentItemClasses": [],
        "WFWorkflowTypes": [],
        "WFWorkflowIsDisabledOnLockScreen": True,
    }
    return plistlib.dumps(workflow, fmt=plistlib.FMT_BINARY, sort_keys=False)


def build_validation_xml(credential: str = "TEST-CREDENTIAL") -> bytes:
    workflow = plistlib.loads(build_backup_shortcut(credential))
    return plistlib.dumps(workflow, fmt=plistlib.FMT_XML, sort_keys=False)
