[Unit]
OnFailure=david-pi-healthcheck-failure@backup.service

[Service]
ExecStartPre=-/usr/bin/systemctl start david-pi-healthcheck-start@backup.service
ExecStartPost=-/usr/bin/systemctl start david-pi-healthcheck-success@backup.service
