import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';
const source=readFileSync(new URL('../static/audiobook-progress.js',import.meta.url),'utf8');
const DAVID='d'.repeat(32),DIANA='e'.repeat(32);
function fixture(initial=null){const values=new Map();if(initial!==null)values.set('david-pi-audiobook-progress-v3',initial);const storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};const context={localStorage:storage};context.globalThis=context;vm.runInNewContext(source,context);return{create:scope=>context.DavidPiAudiobookProgress.create(scope,storage),values};}
test('stores only opaque scoped content-neutral fields',()=>{const{create,values}=fixture();create(DAVID).mark('a'.repeat(32),125.5,false,1000,{title:'secret'});const decoded=JSON.parse(values.get('david-pi-audiobook-progress-v3'));assert.deepEqual(Object.keys(decoded[0]).sort(),['book_id','completed','dirty','position','scope','timestamp']);assert.equal(decoded[0].scope,DAVID);assert.equal(JSON.stringify(decoded).includes('secret'),false);});
test('never crosses identities or adopts unsafe legacy data',()=>{const{create,values}=fixture();values.set('david-pi-audiobook-progress-v1',JSON.stringify([{book_id:'a'.repeat(32),position:99}]));values.set('david-pi-audiobook-progress-v2',JSON.stringify([{scope:DAVID,book_id:'a'.repeat(32),position:88,dirty:true,timestamp:1}]));create(DAVID).mark('a'.repeat(32),10,false,1);create(DIANA).mark('a'.repeat(32),20,false,2);assert.equal(create(DAVID).pending('a'.repeat(32)).position,10);assert.equal(create(DIANA).pending('a'.repeat(32)).position,20);assert.equal(values.has('david-pi-audiobook-progress-v1'),false);assert.equal(values.has('david-pi-audiobook-progress-v2'),false);assert.equal(create('').dirtyEntries().length,0);});
test('acknowledgement cannot erase a newer position',()=>{const{create}=fixture();const queue=create(DAVID),id='c'.repeat(32),first=queue.mark(id,10,false,1000);queue.mark(id,20,false,2000);queue.remove(id,first.timestamp);assert.equal(queue.pending(id).position,20);queue.remove(id,2000);assert.equal(queue.pending(id),null);});
test('bounds all scopes to newest one hundred entries',()=>{const{create}=fixture();for(let index=0;index<105;index++)create(index%2?DAVID:DIANA).mark(index.toString(16).padStart(32,'0'),index,false,index+1);assert.equal(create(DAVID).dirtyEntries().length+create(DIANA).dirtyEntries().length,100);});
