import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import test from'node:test';import vm from'node:vm';
const source=readFileSync(new URL('../static/audiobook-offline-web.js',import.meta.url),'utf8'),encoder=new TextEncoder(),decoder=new TextDecoder(),testSha='0'.repeat(64);
// Execute the shipped worker protocol as well as the page API. This fixture
// supplies browser storage. Protocol fixtures use a deterministic digest; the
// integrity tests below execute the shipped incremental SHA-256 implementation.
function loadApi(storage, fetchImpl=async()=>{throw new Error('unexpected fetch')}, {serviceWorker, realHash=false}={}) {
  const locks={request:(_name,_options,operation)=>operation()};
  let digest={create:()=>({update(){},hex:()=>testSha}),digestFile:async()=>testSha};
  if (realHash) {
    const hashing={module:{exports:{}},Uint8Array,Uint32Array};
    vm.runInNewContext(readFileSync(new URL('../static/sha256-stream.js',import.meta.url),'utf8'),hashing);
    digest=hashing.module.exports;
  }
  class BrowserWorker {
    constructor(url) {
      assert.equal(url,'/static/audiobook-offline-worker.js?v=1');
      const workerSelf={DavidPiSha256:digest,postMessage:data=>queueMicrotask(()=>this.onmessage?.({data}))};
      this.context={self:workerSelf,navigator:{storage},Date,Uint8Array,
        importScripts:url=>assert.equal(url,'/static/sha256-stream.js?v=1')};
      vm.runInNewContext(readFileSync(new URL('../static/audiobook-offline-worker.js',import.meta.url),'utf8'),this.context);
    }
    postMessage(data){this.context.self.onmessage({data});}
    terminate(){vm.runInNewContext('close()',this.context);}
  }
  const browser={isSecureContext:true,navigator:{storage,locks,...(serviceWorker?{serviceWorker}: {})},location:{origin:'https://david-pi.test'},URL,Blob,Worker:BrowserWorker,DavidPiSha256:digest};
  const context={module:{exports:{}},globalThis:browser,URL,Blob,Date,Uint8Array,AbortController,setTimeout,clearTimeout,fetch:fetchImpl};
  vm.runInNewContext(source,context);
  return context.module.exports;
}
function memoryStorage(initial={},removeFailure='',estimate={quota:10_000_000_000,usage:0}){
 const files=new Map(Object.entries(initial).map(([name,value])=>[name,typeof value==='string'?encoder.encode(value):new Uint8Array(value)]));
 const directory={async getFileHandle(name,options={}){if(!files.has(name)&&!options.create){const e=new Error('not found');e.name='NotFoundError';throw e;}if(!files.has(name))files.set(name,new Uint8Array());return{async createSyncAccessHandle(){return{
 getSize:()=>files.get(name).byteLength,
 truncate(size){const grown=new Uint8Array(size);grown.set(files.get(name).subarray(0,size));files.set(name,grown);},
 read(bytes,{at}){const source=files.get(name).subarray(at,at+bytes.byteLength);bytes.set(source);return source.byteLength;},
 write(bytes,{at}){const grown=new Uint8Array(Math.max(files.get(name).byteLength,at+bytes.byteLength));grown.set(files.get(name));grown.set(bytes,at);files.set(name,grown);return bytes.byteLength;},
 flush(){},close(){}
};},async getFile(){const bytes=files.get(name);return new Blob([bytes],{type:name.endsWith('.json')?'application/json':'audio/mpeg'});},async createWritable(options={}){let working=options.keepExistingData?files.get(name).slice():new Uint8Array(),position=0;return{async seek(value){position=value;},async truncate(size){working=working.slice(0,size);},async write(value){const bytes=typeof value==='string'?encoder.encode(value):new Uint8Array(value),grown=new Uint8Array(Math.max(working.byteLength,position+bytes.byteLength));grown.set(working);grown.set(bytes,position);working=grown;position+=bytes.byteLength;},async close(){files.set(name,working);},async abort(){}};}};},async removeEntry(name){if(name===removeFailure)throw new Error('disk busy');if(!files.delete(name)){const e=new Error('not found');e.name='NotFoundError';throw e;}},async*entries(){for(const name of [...files.keys()])yield[name,{name}];}};
 const storageRoot={async getDirectoryHandle(_name,options={}){if(options.create===false&&files.size===0){const e=new Error('not found');e.name='NotFoundError';throw e;}return directory;},async removeEntry(){files.clear();}};
 return{files,storage:{getDirectory:async()=>storageRoot,estimate:async()=>estimate,persist:async()=>true,persisted:async()=>true}};
}
function headers(values){return{get:name=>values[name.toLowerCase()]??null};}
function responses(bytes,etag='"v1"',rangeStart=0){let emitted=false;return async(_url,options={})=>options.method==='HEAD'?{ok:true,status:200,headers:headers({'content-length':String(bytes.length),'accept-ranges':'bytes',etag})}:{ok:true,status:rangeStart?206:200,headers:headers({'content-length':String(bytes.length-rangeStart),etag,...(rangeStart?{'content-range':`bytes ${rangeStart}-${bytes.length-1}/${bytes.length}`}:{})}),body:{getReader:()=>({read:async()=>emitted?{done:true}:(emitted=true,{done:false,value:new Uint8Array(bytes.slice(rangeStart))})})}};}
function book(id,size){return{id,title:'Book',visibility:'shared',byte_size:size,download_url:`/api/audiobooks/${id}/download`,progress_scope:'f'.repeat(32),sha256:testSha,content_sha256:testSha};}
test('shared-only and exact same-book URL gate',async()=>{const memory=memoryStorage(),api=loadApi(memory.storage,responses([1]));assert.equal(api.canSaveBook({visibility:'private'}),false);await assert.rejects(api.save({...book('a'.repeat(32),1),download_url:'/api/audiobooks/'+('b'.repeat(32))+'/download'}),/source is invalid/);});
test('fresh save records a validator-bound complete copy',async()=>{const id='a'.repeat(32),memory=memoryStorage(),api=loadApi(memory.storage,responses([1,2,3]));await api.save(book(id,3));const record=JSON.parse(decoder.decode(memory.files.get(`${id}.json`)));assert.equal(record.state,'complete');assert.equal(record.validator.value,'"v1"');assert.deepEqual([...memory.files.get(`${id}.audio.part`)],[1,2,3]);assert.equal((await api.list())[0].id,id);});
test('resume sends If-Range and requires matching range validator',async()=>{const id='b'.repeat(32),partial={version:2,state:'partial',expected_bytes:4,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(id,4)};const memory=memoryStorage({[`${id}.audio.part`]:[1,2],[`${id}.json`]:JSON.stringify(partial)}),calls=[];const impl=responses([1,2,3,4],'"v1"',2);const api=loadApi(memory.storage,async(url,options)=>{calls.push(options);return impl(url,options);});assert.equal((await api.save(book(id,4))).resumed,true);assert.equal(calls[1].headers.Range,'bytes=2-');assert.equal(calls[1].headers['If-Range'],'"v1"');});
test('resume reserves a whole OPFS replacement in addition to the charged partial',async()=>{const id='8'.repeat(32),total=100,written=80,partial={version:2,state:'partial',expected_bytes:total,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(id,total)},initial={[`${id}.audio.part`]:new Array(written).fill(7),[`${id}.json`]:JSON.stringify(partial)},reserve=128*1024*1024,quota=written+(total-written)+reserve,memory=memoryStorage(initial,'',{quota,usage:written}),calls=[],impl=responses(new Array(total).fill(7),'"v1"',written),api=loadApi(memory.storage,async(url,options)=>{calls.push(options);return impl(url,options);});await assert.rejects(api.save(book(id,total)),/enough browser storage/);assert.equal(calls.length,1);assert.equal(memory.files.get(`${id}.audio.part`).byteLength,written);assert.equal(JSON.parse(decoder.decode(memory.files.get(`${id}.json`))).state,'partial');});
test('resume proceeds when quota covers the charged partial plus a full replacement and reserve',async()=>{const id='9'.repeat(32),total=100,written=80,partial={version:2,state:'partial',expected_bytes:total,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(id,total)},initial={[`${id}.audio.part`]:new Array(written).fill(7),[`${id}.json`]:JSON.stringify(partial)},reserve=128*1024*1024,memory=memoryStorage(initial,'',{quota:written+total+reserve,usage:written}),api=loadApi(memory.storage,responses(new Array(total).fill(7),'"v1"',written));assert.equal((await api.save(book(id,total))).resumed,true);assert.equal(memory.files.get(`${id}.audio.part`).byteLength,total);});
test('capacity arithmetic rejects nonfinite unsafe and overflowing estimates',()=>{const api=loadApi(memoryStorage().storage);assert.equal(api.hasCapacity(1,{quota:Infinity,usage:0}),false);assert.equal(api.hasCapacity(1,{quota:Number.MAX_SAFE_INTEGER,usage:Number.MAX_SAFE_INTEGER}),false);assert.equal(api.hasCapacity(1,{quota:1000,usage:NaN}),false);assert.equal(api.hasCapacity(Number.MAX_SAFE_INTEGER,{quota:Number.MAX_SAFE_INTEGER,usage:0}),false);});
test('changed validator resets partial before requesting a full verified copy',async()=>{const id='c'.repeat(32),partial={version:2,state:'partial',expected_bytes:3,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"old"'},book:book(id,3)};const memory=memoryStorage({[`${id}.audio.part`]:[9],[`${id}.json`]:JSON.stringify(partial)}),api=loadApi(memory.storage,responses([1,2,3],'"new"'));await api.save(book(id,3));assert.deepEqual([...memory.files.get(`${id}.audio.part`)],[1,2,3]);});
test('complete re-save and failed deletion preserve truthful metadata',async()=>{const id='d'.repeat(32),record={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:1,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(id,1)};const memory=memoryStorage({[`${id}.audio.part`]:[1],[`${id}.json`]:JSON.stringify(record)},`${id}.audio.part`),api=loadApi(memory.storage,responses([1]));await assert.rejects(api.save(book(id,1)),/already saved/);await assert.rejects(api.remove(id),/disk busy/);const retained=JSON.parse(decoder.decode(memory.files.get(`${id}.json`)));assert.equal(retained.state,'partial');});
test('corrupt or partial remnants are discoverable and bulk removable',async()=>{const memory=memoryStorage({'broken.json':'{bad','orphan.audio.part':[1]}),api=loadApi(memory.storage);assert.equal((await api.list()).length,0);assert.equal(await api.hasStoredData(),true);await api.removeAll();assert.equal(await api.hasStoredData(),false);});
test('one hundred complete books refuse a new save without eviction',async()=>{const initial={};for(let i=0;i<100;i++){const id=i.toString(16).padStart(32,'0'),record={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:1,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"x"'},book:book(id,1)};initial[`${id}.json`]=JSON.stringify(record);initial[`${id}.audio.part`]=[1];}const memory=memoryStorage(initial),api=loadApi(memory.storage,responses([1]));await assert.rejects(api.save(book('f'.repeat(32),1)),/100 saved books/);assert.equal((await api.list()).length,100);});
test('full media with partial metadata finalizes without a zero-byte range request',async()=>{const id='1'.repeat(32),partial={version:2,state:'partial',expected_bytes:3,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(id,3)};const memory=memoryStorage({[`${id}.audio.part`]:[1,2,3],[`${id}.json`]:JSON.stringify(partial)}),calls=[];const api=loadApi(memory.storage,async(url,options)=>{calls.push(options);return responses([1,2,3])(url,options);});const result=await api.save(book(id,3));assert.equal(result.recovered,true);assert.equal(calls.length,1);assert.equal(JSON.parse(decoder.decode(memory.files.get(`${id}.json`))).state,'complete');});
test('a complete record with missing media is repaired by Save',async()=>{const id='2'.repeat(32),complete={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:3,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(id,3)};const memory=memoryStorage({[`${id}.json`]:JSON.stringify(complete)}),api=loadApi(memory.storage,responses([1,2,3]));assert.equal((await api.list()).length,0);await api.save(book(id,3));assert.deepEqual([...memory.files.get(`${id}.audio.part`)],[1,2,3]);assert.equal((await api.list()).length,1);});
test('explicit Save safely rebinds an intact copy to the current stable scope',async()=>{const id='3'.repeat(32),old={...book(id,2),progress_scope:'e'.repeat(32),position_seconds:900},complete={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:2,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:old};const memory=memoryStorage({[`${id}.audio.part`]:[4,5],[`${id}.json`]:JSON.stringify(complete)}),api=loadApi(memory.storage,responses([4,5]));const result=await api.save({...book(id,2),position_seconds:42});const rebound=JSON.parse(decoder.decode(memory.files.get(`${id}.json`)));assert.equal(result.rebound,true);assert.equal(rebound.book.progress_scope,'f'.repeat(32));assert.equal(rebound.book.position_seconds,42);assert.deepEqual([...memory.files.get(`${id}.audio.part`)],[4,5]);});
test('legacy migration retains every unresolved manifest entry',async()=>{const migrated='4'.repeat(32),missing='5'.repeat(32),privateId='6'.repeat(32);const legacy={books:[book(migrated,2),book(missing,2),{...book(privateId,2),visibility:'private'}]};const memory=memoryStorage({'library.json':JSON.stringify(legacy),[`${migrated}.audio`]:[7,8]}),api=loadApi(memory.storage);const listed=await api.list();assert.equal(listed.length,1);assert.equal(listed[0].progress_scope,'');const remaining=JSON.parse(decoder.decode(memory.files.get('library.json')));assert.equal(remaining.migration_pending,true);assert.deepEqual(remaining.books.map(item=>item.id),[missing,privateId]);});
test('legacy migration keeps its recovery entry when replacement metadata points to missing media',async()=>{const id='7'.repeat(32),replacement={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:2,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(id,2)};const memory=memoryStorage({'library.json':JSON.stringify({books:[book(id,2)]}),[`${id}.json`]:JSON.stringify(replacement)}),api=loadApi(memory.storage);assert.equal((await api.list()).length,0);const retained=JSON.parse(decoder.decode(memory.files.get('library.json')));assert.equal(retained.migration_pending,true);assert.equal(retained.books[0].id,id);});

test('inventory truthfully separates playable and resumable copies with storage readiness',async()=>{const completeId='a'.repeat(32),partialId='b'.repeat(32),complete={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:3,file_name:`${completeId}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(completeId,3)},partial={version:2,state:'partial',expected_bytes:10,file_name:`${partialId}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(partialId,10)},memory=memoryStorage({[`${completeId}.audio.part`]:[1,2,3],[`${completeId}.json`]:JSON.stringify(complete),[`${partialId}.audio.part`]:[1,2,3,4],[`${partialId}.json`]:JSON.stringify(partial),'orphan.audio.part':[9]},'',{quota:1000,usage:50}),api=loadApi(memory.storage),inventory=await api.inventory();assert.equal(inventory.supported,true);assert.equal(inventory.complete_count,1);assert.equal(inventory.partial_count,1);assert.equal(inventory.complete_bytes,3);assert.equal(inventory.partial_bytes,4);assert.equal(inventory.available_bytes,950);assert.equal(inventory.persistent,true);assert.equal(inventory.has_data,true);assert.equal(inventory.has_unresolved_data,true);assert.equal(inventory.books[0].id,completeId);assert.equal(inventory.partials[0].id,partialId);assert.equal(inventory.partials[0].downloaded_bytes,4);assert.equal(inventory.partials[0].expected_bytes,10);});

test('automatic playback exposes only an intact verified copy bound to the current identity scope',async()=>{const id='c'.repeat(32),scope='f'.repeat(32),complete={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:3,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:{...book(id,3),position_seconds:61}},memory=memoryStorage({[`${id}.audio.part`]:[1,2,3],[`${id}.json`]:JSON.stringify(complete)}),api=loadApi(memory.storage);const playable=await api.playable(id,scope);assert.equal(playable.id,id);assert.equal(playable.position_seconds,61);assert.equal(playable.local_url,`/__davidpi_offline/audiobooks/${id}`);assert.equal(await api.playable(id,'e'.repeat(32)),null);memory.files.set(`${id}.audio.part`,new Uint8Array([1,2]));assert.equal(await api.playable(id,scope),null);});

test('identity-bound position updates cannot rewrite another scope saved copy',async()=>{const id='d'.repeat(32),complete={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:1,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:{...book(id,1),position_seconds:5}},memory=memoryStorage({[`${id}.audio.part`]:[1],[`${id}.json`]:JSON.stringify(complete)}),api=loadApi(memory.storage);await api.updatePosition(id,99,false,'e'.repeat(32));assert.equal(JSON.parse(decoder.decode(memory.files.get(`${id}.json`))).book.position_seconds,5);await api.updatePosition(id,77,false,'f'.repeat(32));assert.equal(JSON.parse(decoder.decode(memory.files.get(`${id}.json`))).book.position_seconds,77);});

test('verified same-scope playback falls back to an OPFS Blob URL without a controlling worker',async()=>{const id='e'.repeat(32),scope='f'.repeat(32),complete={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:3,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(id,3)},memory=memoryStorage({[`${id}.audio.part`]:[1,2,3],[`${id}.json`]:JSON.stringify(complete)}),api=loadApi(memory.storage),source=await api.playbackSource(id,scope);assert.equal(source.transport,'object-url');assert.match(source.playback_url,/^blob:/);assert.equal(source.revoke_url,true);api.releasePlaybackSource(source);assert.equal(await api.playbackSource(id,'e'.repeat(32)),null);});

test('normal playback atomically adopts a verified legacy unscoped copy for seamless progress',async()=>{const id='4'.repeat(32),scope='f'.repeat(32),legacyBook={...book(id,2),progress_scope:'',position_seconds:73},complete={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:2,file_name:`${id}.audio`,validator:{type:'legacy',value:'size-2'},book:legacyBook},memory=memoryStorage({[`${id}.audio`]:[7,8],[`${id}.json`]:JSON.stringify(complete)}),api=loadApi(memory.storage),source=await api.playbackSource(id,scope);assert.equal(source.progress_scope,scope);assert.equal(source.position_seconds,73);const rebound=JSON.parse(decoder.decode(memory.files.get(`${id}.json`)));assert.equal(rebound.book.progress_scope,scope);api.releasePlaybackSource(source);assert.equal(await api.playbackSource(id,'e'.repeat(32)),null);});

test('offline manager keeps verified legacy unbound records playable through Blob fallback',async()=>{const id='1'.repeat(32),legacyBook={...book(id,2),progress_scope:''},complete={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:2,file_name:`${id}.audio`,validator:{type:'legacy',value:'size-2'},book:legacyBook},memory=memoryStorage({[`${id}.audio`]:[7,8],[`${id}.json`]:JSON.stringify(complete)}),api=loadApi(memory.storage);const source=await api.managerPlaybackSource(id);assert.equal(source.id,id);assert.equal(source.transport,'object-url');api.releasePlaybackSource(source);});

test('a controlling service worker uses its verified local byte-range route',async()=>{const id='2'.repeat(32),scope='f'.repeat(32),complete={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:3,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(id,3)},memory=memoryStorage({[`${id}.audio.part`]:[1,2,3],[`${id}.json`]:JSON.stringify(complete)}),fetchImpl=async(_url,options={})=>options.method==='HEAD'?{ok:true,headers:headers({'accept-ranges':'bytes','content-length':'3'})}:{status:206,headers:headers({'content-range':'bytes 0-0/3'}),arrayBuffer:async()=>new Uint8Array([1]).buffer},api=loadApi(memory.storage,fetchImpl,{serviceWorker:{controller:{}}}),source=await api.playbackSource(id,scope);assert.equal(source.transport,'service-worker');assert.equal(source.playback_url,`/__davidpi_offline/audiobooks/${id}`);assert.equal(source.revoke_url,false);});

test('a stale controlling worker cannot strand a verified copy at zero duration',async()=>{const id='3'.repeat(32),scope='f'.repeat(32),complete={version:3,state:'complete',content_sha256:testSha,integrity_verified_at:1,expected_bytes:2,file_name:`${id}.audio.part`,validator:{type:'etag',value:'"v1"'},book:book(id,2)},memory=memoryStorage({[`${id}.audio.part`]:[8,9],[`${id}.json`]:JSON.stringify(complete)}),api=loadApi(memory.storage,async()=>{throw new Error('stale worker route')},{serviceWorker:{controller:{}}}),source=await api.playbackSource(id,scope);assert.equal(source.transport,'object-url');assert.match(source.playback_url,/^blob:/);api.releasePlaybackSource(source);});


test('shipped storage worker verifies actual bytes before declaring an offline copy complete',async()=>{
  const id='a'.repeat(32),bytes=[1,2,3,255],sha=createHash('sha256').update(Buffer.from(bytes)).digest('hex');
  const memory=memoryStorage(),api=loadApi(memory.storage,responses(bytes),{realHash:true});
  await api.save({...book(id,bytes.length),sha256:sha,content_sha256:sha});
  const saved=JSON.parse(decoder.decode(memory.files.get(`${id}.json`)));
  assert.equal(saved.state,'complete');assert.equal(saved.content_sha256,sha);
  assert.deepEqual([...memory.files.get(`${id}.audio.part`)],bytes);
});
test('shipped storage worker rejects changed bytes and never exposes them as a completed book',async()=>{
  const id='b'.repeat(32),memory=memoryStorage(),api=loadApi(memory.storage,responses([1,2,3]),{realHash:true});
  await assert.rejects(api.save(book(id,3)),/integrity check/);
  assert.equal((await api.list()).length,0);
  const saved=JSON.parse(decoder.decode(memory.files.get(`${id}.json`)));
  assert.notEqual(saved.state,'complete');
});
