[Unit]
OnFailure=david-pi-healthcheck-failure@server-status.service

[Service]
ExecStartPre=-/usr/bin/systemctl start david-pi-healthcheck-start@server-status.service
ExecStartPost=-/usr/bin/systemctl start david-pi-healthcheck-success@server-status.service
