[Unit]
OnFailure=david-pi-healthcheck-failure@b2-backup.service

[Service]
ExecStartPre=-/usr/bin/systemctl start david-pi-healthcheck-start@b2-backup.service
ExecStartPost=-/usr/bin/systemctl start david-pi-healthcheck-success@b2-backup.service
