[Unit]
OnFailure=david-pi-healthcheck-failure@data-backup.service

[Service]
ExecStartPre=-/usr/bin/systemctl start david-pi-healthcheck-start@data-backup.service
ExecStartPost=-/usr/bin/systemctl start david-pi-healthcheck-success@data-backup.service
